Create sample_manifest_extended.json
HadrienGardeur/audiobook-manifest pull request #14
Opened 2017-04-06 21:02 UTC by daryanypl

Adding the options we talked about on slack into a sample manifest file, so we can see how the whole thing might look.

2017-04-07 13:27 UTC, HadrienGardeur requested changes
There are quite a few problems with this example, I've reviewed all of them and addressed them in comments.

2017-04-07 13:27 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +    }
There's a missing ,

2017-04-07 13:27 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +    "typicalAgeRange": "7-11",
This should be `schema:typicalAgeRange`

2017-04-07 13:27 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +    "samplerate": "22KHz",
Do we need the unit for samplerate? We don't include any for bitrate for example, we default to kb/s

2017-04-07 13:27 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +        "role": ["aut"]
Don't use `contributor` when you can use `author`

2017-04-07 13:27 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +        "role": ["led"]
Not sure why we're using that role here.

2017-04-07 13:27 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +        "role": ["nrt"]
These last two contributors should use the `narrator` element instead.

2017-04-07 13:27 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +            "@type": "http://schema.org/Book",
If it's the original source materials, it shouldn't be in `hasPart`.

2017-04-07 13:27 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +            "schema:license": "https://creativecommons.org/publicdomain/zero/1.0/"
If this is the license for the current audiobook, it shouldn't be in `hasPart` either.

2017-04-07 13:27 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +    ]
There's a missing ,

2017-04-07 13:27 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +    {"rel": "renew", "href": "http://example.org/license/35d9b2d6/renew{?end,id,name}", "type": "application/vnd.readium.lcp.license.v1.0+json", "templated": true},
I'm not sure why there's a link to an LCP license and no information about the files being encrypted.

Also, the other links wouldn't show up directly in the manifest with LCP.

2017-04-07 13:27 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +        "schema:hasPart": [
You can't do that with our current model. If the goal is to provide the narrator for a specific resource, this should be in the metadata section above as:
```
"schema:hasPart": [
  {
    "schema:url": "http://www.archive.org/download/flatland_rg_librivox/flatland_1_abbott.mp3",
    "narrator": "Abe Narrator"
  }
]
```

2017-04-07 13:27 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +        "schema:hasPart": [
Same comment as for the example above.

2017-04-07 18:25 UTC, daryanypl commented on examples/sample_manifest_extended.json
> +    "samplerate": "22KHz",
Maybe not.  Sample rates usually go from 8.5KHz to 128KHz.  If we either allow real numbers or express the rate in Hz, we won't need units.  I'll switch to a real number.

2017-04-07 18:46 UTC, daryanypl commented on examples/sample_manifest_extended.json
> +        "role": ["aut"]
https://github.com/HadrienGardeur/audiobook-manifest/issues/9 for more

2017-04-07 19:22 UTC, daryanypl commented on examples/sample_manifest_extended.json
> +            "@type": "http://schema.org/Book",
The conversation that led to this element, was us trying to figure out how to indicate the licensing of book parts, such as illustration.  For Librivox books, what we can have is a free book and audio recording, and a restricted art work.  Would there be a better way to reflect that?

2017-04-07 19:33 UTC, daryanypl commented on examples/sample_manifest_extended.json
> +    {"rel": "renew", "href": "http://example.org/license/35d9b2d6/renew{?end,id,name}", "type": "application/vnd.readium.lcp.license.v1.0+json", "templated": true},
adjusted

2017-04-07 19:46 UTC, daryanypl commented on examples/sample_manifest_extended.json
> +        "schema:hasPart": [
fixed

2017-04-08 12:05 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +            "@type": "http://schema.org/Book",
The first element is fine, I'm just confused about the other two resources listed in hasPart.

2017-04-08 12:11 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +        "scheme": "https://www.loc.gov/marc/relators/",
No need for `scheme` here or in the other elements since we're not using contributor.

2017-04-08 12:11 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +    {"rel": "alternate", "href": "https://[...]/appendix.pdf", "type": "application/pdf"},
Should be `"rel": "related"` based on our latest discussions.

2017-04-08 12:11 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +        "bitrate": 128,
We repeat `bitrate` but not `samplerate` and `channels`. Maybe we should avoid repeating any of these elements at a link level if they don't differ from the ones expressed in `metadata`?

2017-04-10 18:13 UTC, daryanypl commented on examples/sample_manifest_extended.json
> +            "@type": "http://schema.org/Book",
I was trying to reflect the state of having three separate licenses for the parts of the book that usually have licenses: art, text, and narration.  
For the narration part, would you prefer to use the license element that's a direct child of "metadata"?  We can do that, if we set it as a formal assumption that that more general element refers to either the entire production, or just the audiobook, depending on whether a hasPart license for illustration is present.
For the Book part, I'm not sure how else to specify it.  We can sometimes point to the original source material (with the related link we discussed), but only if we have ingested that material.  I think it's a good idea to have the licenses the audiobook came with stay with the audiobook.

2017-04-10 18:13 UTC, daryanypl commented on examples/sample_manifest_extended.json
> +    {"rel": "alternate", "href": "https://[...]/appendix.pdf", "type": "application/pdf"},
changed

2017-04-10 18:13 UTC, daryanypl commented on examples/sample_manifest_extended.json
> +        "scheme": "https://www.loc.gov/marc/relators/",
fixed

2017-04-10 18:14 UTC, daryanypl commented on examples/sample_manifest_extended.json
> +        "bitrate": 128,
Good point.

2017-04-10 19:57 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +            "@type": "http://schema.org/Book",
Honestly, I don't really see how to express rights for text vs narration without going down a very complex path.

I would limit the example to the cover for now.

2017-04-10 20:02 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +        "sort_as": {
I understand why you included multiple languages in `sort_as`, but I'm not sure that's a good thing to have. I really don't know how apps could handle that well.

2017-04-10 20:02 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +    "narrator": [
For `narrator`, `illustrator` and `translator`, now that you only include `name`, a mort straightforward syntax could be used:

```
"narrator": ["Abe Narrator", "Beatrice Narrator"]
```

2017-04-10 20:02 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +    "schema:hasPart": [
Why do we repeat `schema:hasPart`? That's not something that we can do in JSON.

2017-04-10 20:27 UTC, daryanypl commented on examples/sample_manifest_extended.json
> +        "sort_as": {
We carry books in Spanish, Russian, Chinese, etc..  We do not currently have the ability to display the author name based on the user's system language preferences.  Making sure that we keep a place for the versions of author's names to be kept is one of the steps in solving the problem.

2017-04-10 20:28 UTC, daryanypl commented on examples/sample_manifest_extended.json
> +    "narrator": [
Sure.  Are there any other properties that a narrator field could have inside?

2017-04-10 20:30 UTC, daryanypl commented on examples/sample_manifest_extended.json
> +            "@type": "http://schema.org/Book",
I think we'll need this.  Rights handling can and will be done in database on the server side, but it's a basic part of our functionality, and is bound to find its way into the manifest.  Better we provide a clean way now than scramble with additions later.

2017-04-10 20:37 UTC, daryanypl commented on examples/sample_manifest_extended.json
> +            "schema:license": "https://creativecommons.org/publicdomain/zero/1.0/"
Where would you want it to be?

2017-04-10 20:38 UTC, daryanypl commented on examples/sample_manifest_extended.json
> +    "schema:hasPart": [
Ah, that is an artifact of me having to edit the file externally and then copy-pasting into here.  Removed.

2017-04-10 21:02 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +        "sort_as": {
I'm strongly in favour of keeping that for displaying the author name, the issue I have is with using them in `sort_as`.

2017-04-10 21:03 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +    "narrator": [
Sure, it's just that when there are no additional properties, we can use a more compact syntax.

2017-04-10 21:03 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +            "@type": "http://schema.org/Book",
We can't truly scramble since this is entirely extensible using any number of external vocabularies.

2017-04-10 21:04 UTC, HadrienGardeur commented on examples/sample_manifest_extended.json
> +            "schema:license": "https://creativecommons.org/publicdomain/zero/1.0/"
I would argue that we already have this info below in `schema:license`.

2017-04-13 18:40 UTC, daryanypl commented on examples/sample_manifest_extended.json
> +        "sort_as": {
As agreed offline, removed for now, and added as an issue on Readium Webpub Manifest tracker.

2017-04-21 17:10 UTC, merged